Repository DeokJong/JBNU-SHOPPING, pull requests merged in 2024-10, with the labels that each got.

#2 feature: backend docker file and project root docker-compose.yml
  backend/.dockerignore
  backend/Dockerfile
  docker-compose.yml
Labels: documentation

#5 Docs/readme.md
  README.md
Labels: documentation

#9 Feature/login
  backend/build.gradle
  backend/src/main/java/com/cottongallery/backend/auth/config/CorsConfig.java
  backend/src/main/java/com/cottongallery/backend/auth/config/SecurityConfig.java
  backend/src/main/java/com/cottongallery/backend/constants/Role.java
  backend/src/main/java/com/cottongallery/backend/controller/AccountController.java
  backend/src/main/java/com/cottongallery/backend/controller/AuthController.java
  backend/src/main/java/com/cottongallery/backend/controller/TestController.java
  backend/src/main/java/com/cottongallery/backend/controller/validator/AccountCreateRequestValidator.java
  backend/src/main/java/com/cottongallery/backend/dto/auth/AuthRequest.java
  backend/src/main/java/com/cottongallery/backend/dto/auth/AuthResponse.java
  backend/src/main/java/com/cottongallery/backend/repository/AccountRepository.java
  backend/src/main/java/com/cottongallery/backend/security/AccountDetails.java
  backend/src/main/java/com/cottongallery/backend/security/AccountDetailsService.java
  backend/src/main/java/com/cottongallery/backend/security/JwtAccessDeniedHandler.java
  backend/src/main/java/com/cottongallery/backend/security/JwtAuthenticationEntryPoint.java
  backend/src/main/java/com/cottongallery/backend/security/JwtAuthenticationFilter.java
  backend/src/main/java/com/cottongallery/backend/security/TokenProvider.java
  backend/src/main/java/com/cottongallery/backend/service/AccountService.java
  backend/src/main/java/com/cottongallery/backend/service/AuthService.java
  backend/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application.yml
Labels: enhancement

#11 AOP 및 인터셉터를 통한 로깅 구현
  backend/src/main/java/com/cottongallery/backend/common/aop/LogAspect.java
  backend/src/main/java/com/cottongallery/backend/common/config/WebConfig.java
  backend/src/main/java/com/cottongallery/backend/common/interceptor/LogInterceptor.java
  backend/src/main/resources/application.yml
Labels: enhancement

#14 우편번호 필드 타입 Integer에서 String으로 변경
  backend/src/main/java/com/cottongallery/backend/auth/dto/account/request/AccountCreateRequest.java
  backend/src/main/java/com/cottongallery/backend/common/domain/Address.java
  backend/src/test/java/com/cottongallery/backend/controller/AccountControllerTest.java
  backend/src/test/java/com/cottongallery/backend/util/AccountTestData.java
Labels: bug

#13 Feature/fe/auth
  frontend/package.json
  frontend/src/app/(auth)/_components/InputBox.tsx
  frontend/src/app/(auth)/_components/Login.tsx
  frontend/src/app/(auth)/_components/SignUp.tsx
  frontend/src/app/(auth)/_components/SubmitBtn.tsx
  frontend/src/app/(auth)/login/page.tsx
  frontend/src/app/api/login/route.ts
  frontend/src/store/authStore.ts
  frontend/src/types/auth.type.ts
  frontend/yarn.lock
Labels: enhancement

#17 사용자 정보 주입 ArgumentResolver 구현
  backend/src/main/java/com/cottongallery/backend/auth/controller/TestController.java
  backend/src/main/java/com/cottongallery/backend/common/argumentResolver/LoginAccountArgumentResolver.java
  backend/src/main/java/com/cottongallery/backend/common/argumentResolver/annotation/Login.java
  backend/src/main/java/com/cottongallery/backend/common/config/WebConfig.java
  backend/src/main/java/com/cottongallery/backend/common/dto/AccountSessionDTO.java
Labels: enhancement

#16 Entity Auditing 기능 구현
  backend/src/main/java/com/cottongallery/backend/BackendApplication.java
  backend/src/main/java/com/cottongallery/backend/auth/domain/Account.java
  backend/src/main/java/com/cottongallery/backend/domain/base/BaseEntity.java
  backend/src/main/java/com/cottongallery/backend/domain/base/BaseTimeEntity.java
Labels: enhancement
